### ISSUE TITLE
Failed to make identity provider oauth callback: java.lang.NullPointerException

### ISSUE THREAD

**Issue by jkasztur** [BenjaminFavre/keycloak-apple-social-identity-provider#24]
Hi, I updated the provider like in this PR https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider/pull/21
to use this in Keycloak 16.1.1

my configuration looks correct accorging to Readme
![Screenshot - 2022-03-29T162255 620](https://user-images.githubusercontent.com/6042169/160633574-f524ec85-96d0-4caa-9e73-c46fdc58d43c.png)

After trying to login, I get redirected to apple, fill credentials, but when getting back to keycloak page, i see `Unexpected error when authenticating with identity provider`
In keycloak logs there is this:
```
14:27:23,462 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-12) Failed to make identity provider oauth callback: java.lang.NullPointerException
	at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.resources.IdentityBrokerService.lambda$authenticated$0(IdentityBrokerService.java:528)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.keycloak.keycloak-services@16.1.1//org.keycloak.services.resources.IdentityBrokerService.authenticated(IdentityBrokerService.java:525)
	at org.keycloak.keycloak-services@16.1.1//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:514)
	at deployment.apple-social-identity-provider-1.0.3-SNAPSHOT.jar//fr.benjaminfavre.provider.AppleIdentityProvider$OIDCEndpoint.authResponse(AppleIdentityProvider.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.resteasy-core@4.7.4.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
...
```

Any idea how to make it work?

**Comment by JayAhn2** [comment]
@jkasztur have you find the way to solve it?

**Comment by ssorrychoi** [comment]
I have also same issue :( Help me...

**Comment by jkasztur** [comment]
I found out I had a broken mapper in apple provider(dont remember how broken). But if I remember correctly, all I did is delete mapper/all mappers and recreate them
